services:
  interview-service:
    build:
      dockerfile: Dockerfile
    container_name: interview-service
    depends_on:
      postgres-mockinterview:
        condition: service_healthy
      minio-mockinterview:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres-mockinterview:5432/postgres
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}
      - YANDEX_REDIRECT_URI=${YANDEX_REDIRECT_URI}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - MINIO_ENDPOINT=http://minio-mockinterview:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    networks:
      - microservices-network
    restart: unless-stopped

  postgres-mockinterview:
    image: postgres:15-alpine
    container_name: postgres-mockinterview
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-interview-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio-mockinterview:
    image: minio/minio:latest
    container_name: minio-mockinterview
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres-interview-data:
  minio-data:
